name: Build OrangeFox Patch Boot
on:
  workflow_dispatch:

env:
  FOX_BRANCH: "12.1"
  DEVICE_CODENAME: "L39_IVVI_4_64_V80M60BP_NZW_BT30"
  DT_REPO: "xyyyico/device-5g-L39_IVVI_4_64_V80M60BP_NZW_BT30"
  DT_BRANCH: "main"
  FOX_PATCH_STOCK_BOOT: true
  STOCK_BOOT_DL_URL: "https://github.com/xyyyico/device-5g-L39_IVVI_4_64_V80M60BP_NZW_BT30/releases/download/stock/boot.img"
  ALLOW_MISSING_DEPENDENCIES: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 编译橙狐+自动修补boot
        uses: momo54181/Lazy_Action-Recoverys-Builder@main
        with:
          build_type: OFRP
          fox_branch: 12.1
          dt_url: https://github.com/${{ env.DT_REPO }}.git
          dt_branch: ${{ env.DT_BRANCH }}
